#!/usr/bin/env python3
"""Check every tracked dependency against its upstream source and update one
persistent GitHub issue with the status table.

Reads dependencies/inventory.json (generated by map_dependencies.py) and
dependencies/sources.yml (for `updates` provider config). Does not touch
GitHub Actions pins -- Dependabot owns those.

The `wordpress-acf` provider (ZWO's 4 product SDKs) additionally verifies the
published artifact against a locally installed version and a persisted
per-dependency snapshot (dependencies/update-state.json), detecting a vendor
silently replacing an already-published download. It downloads the artifact
only to a temporary directory for inspection -- it never writes into
AlpacaCore/external and never replaces a vendored binary. A caller running in
CI is expected to upload that temp directory as a build artifact and discard
it; this script does not do that itself.

Usage:
  python3 scripts/dependencies/check_updates.py [--dry-run] [--no-download]

Requires `gh` authenticated against the target repository unless --dry-run.
"""
from __future__ import annotations

import argparse
import contextlib
import datetime
import hashlib
import json
import re
import subprocess
import sys
import tarfile
import tempfile
import urllib.error
import urllib.request
import zipfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
SOURCES_PATH = REPO_ROOT / "dependencies" / "sources.yml"
INVENTORY_PATH = REPO_ROOT / "dependencies" / "inventory.json"
STATE_PATH = REPO_ROOT / "dependencies" / "update-state.json"
ISSUE_TITLE = "Dependency update status"

sys.path.insert(0, str(Path(__file__).resolve().parent))
from sources import debian, github, manual, static_download_page, svbony, vendor_page, wordpress_acf  # noqa: E402
import map_dependencies  # noqa: E402

PROVIDERS = {
    "debian": debian.latest_version,
    "github-release": github.latest_version,
    "vendor-page": vendor_page.latest_version,
    "release-page": vendor_page.latest_version,
    "manual": manual.latest_version,
}


def load_yaml(path: Path) -> dict:
    import yaml
    return yaml.safe_load(path.read_text())


def load_state() -> dict:
    return json.loads(STATE_PATH.read_text()) if STATE_PATH.exists() else {}


def save_state(state: dict) -> None:
    STATE_PATH.write_text(json.dumps(state, indent=2, sort_keys=True) + "\n")


@contextlib.contextmanager
def _artifact_dir(dep_id: str, artifacts_root: Path | None):
    """Yield a directory to download into. With artifacts_root set (CI), the
    directory is kept so the caller can upload it as a build artifact and
    discard it -- this script never commits it. Without artifacts_root
    (local runs), it's a temp dir cleaned up automatically."""
    if artifacts_root is None:
        with tempfile.TemporaryDirectory(prefix=f"dep-verify-{dep_id}-") as tmp:
            yield Path(tmp)
    else:
        adir = artifacts_root / dep_id
        adir.mkdir(parents=True, exist_ok=True)
        yield adir


def _version_tuple(v: str) -> tuple:
    return tuple(int(p) if p.isdigit() else p for p in re.split(r"[.\-]", v))


def download_artifact(url: str, dest_dir: Path) -> tuple[Path | None, str | None]:
    name = url.rsplit("/", 1)[-1].split("?", 1)[0] or "download.bin"
    dest = dest_dir / name
    req = urllib.request.Request(url, headers={"User-Agent": "alpacabridge-dependency-mapper"})
    try:
        with urllib.request.urlopen(req, timeout=120) as resp, dest.open("wb") as f:
            while True:
                chunk = resp.read(1 << 20)
                if not chunk:
                    break
                f.write(chunk)
    except (urllib.error.URLError, urllib.error.HTTPError, TimeoutError) as exc:
        return None, str(exc)
    except Exception as exc:
        return None, str(exc)
    return dest, None


def inspect_archive(path: Path, expect_glob: str) -> dict:
    """List archive members without executing anything; confirm an ARM64 library
    matching expect_glob is present and extract its embedded version."""
    import fnmatch

    try:
        if tarfile.is_tarfile(path):
            with tarfile.open(path) as tf:
                names = tf.getnames()
        elif zipfile.is_zipfile(path):
            with zipfile.ZipFile(path) as zf:
                names = zf.namelist()
        else:
            return {"readable": False, "reason": "not a recognized tar/zip archive"}
    except Exception as exc:
        return {"readable": False, "reason": str(exc)}

    matches = [n for n in names if fnmatch.fnmatch(n, expect_glob) or fnmatch.fnmatch(Path(n).name, Path(expect_glob).name)]
    if not matches:
        return {"readable": True, "has_expected_library": False, "matches": []}

    version_re = re.compile(r"\.so\.([\d.]+)$")
    versions = sorted({m.group(1) for name in matches if (m := version_re.search(name))})
    return {"readable": True, "has_expected_library": True, "matches": matches, "embedded_versions": versions}


def classify_wordpress_acf(dep: dict, state: dict, do_download: bool, artifacts_root: Path | None) -> dict:
    dep_id = dep["id"]
    entry = wordpress_acf.fetch_entry(dep)
    if entry["status"] != "ok":
        return {"status": entry["status"].upper().replace("-", "_"), "detail": entry.get("detail", "")}

    local_version = map_dependencies.resolve_local_version(dep)
    if local_version is None:
        return {"status": "VERSION_UNKNOWN", "detail": "no local SONAME matched local.version_from"}

    prev = state.get(dep_id, {})
    result = {
        "upstream_version": entry["version"],
        "release_date": entry.get("release_date"),
        "size": entry.get("size"),
        "download_url": entry.get("download_url"),
        "checked_at": datetime.datetime.now(datetime.timezone.utc).isoformat(),
    }

    try:
        version_increased = _version_tuple(entry["version"]) > _version_tuple(local_version)
    except (TypeError, ValueError):
        version_increased = entry["version"] != local_version

    verdict = {"status": "CURRENT", "detail": f"local {local_version}, upstream {entry['version']}"}

    if do_download and dep["updates"].get("verify_download"):
        with _artifact_dir(dep_id, artifacts_root) as adir:
            archive, err = download_artifact(entry["download_url"], adir)
            if archive is None:
                result["sha256"] = prev.get("sha256")
                state[dep_id] = {**prev, **result}
                return {"status": "SOURCE_UNREACHABLE", "detail": f"artifact download failed: {err}"}

            sha256 = hashlib.sha256(archive.read_bytes()).hexdigest()
            result["sha256"] = sha256
            archive_info = inspect_archive(archive, dep["updates"].get("expect_library_glob", "*"))

            if version_increased:
                if not archive_info.get("has_expected_library"):
                    verdict = {"status": "INCOMPATIBLE_UPDATE",
                               "detail": f"upstream {entry['version']} archive has no match for expected library"}
                else:
                    verdict = {"status": "UPDATE_AVAILABLE", "detail": f"{local_version} -> {entry['version']}"}
            else:
                prev_hash = prev.get("sha256")
                if prev_hash and prev_hash != sha256:
                    verdict = {"status": "SILENT_REPLACEMENT",
                               "detail": f"same version {entry['version']} but artifact hash changed "
                                         f"({prev_hash[:12]}... -> {sha256[:12]}...)"}
                else:
                    verdict = {"status": "CURRENT", "detail": f"at latest ({local_version}), hash matches"}
    elif version_increased:
        verdict = {"status": "UPDATE_AVAILABLE", "detail": f"{local_version} -> {entry['version']} (not archive-verified)"}
        result["sha256"] = prev.get("sha256")
    else:
        result["sha256"] = prev.get("sha256")

    state[dep_id] = {**prev, **result}
    return verdict


def classify_static_download_page(dep: dict, state: dict, do_download: bool, artifacts_root: Path | None) -> dict:
    """A protocol-spec PDF on a vendor page (e.g. Sky-Watcher's application
    development downloads): compares title/date/URL/size against the last
    snapshot, and -- since the repo stores a Markdown conversion, not the
    original PDF, so a local file hash can never be compared to it directly
    -- optionally downloads the PDF to detect a same-metadata hash change
    (a silent replacement under the same URL, same publication date)."""
    dep_id = dep["id"]
    entry = static_download_page.fetch_entry(dep)
    if entry["status"] != "ok":
        return {"status": entry["status"].upper().replace("-", "_"), "detail": entry.get("detail", "")}

    prev = state.get(dep_id, {})
    result = {
        "title": entry["title"],
        "download_url": entry["download_url"],
        "size_kb": entry["size_kb"],
        "published_date": entry["published_date"],
        "checked_at": datetime.datetime.now(datetime.timezone.utc).isoformat(),
    }

    metadata_changed = (
        prev.get("download_url") not in (None, entry["download_url"])
        or prev.get("published_date") not in (None, entry["published_date"])
        or prev.get("size_kb") not in (None, entry["size_kb"])
    )

    # Only some of these documents carry an actual version number (e.g.
    # "Synscan Serial Communication Protocol, Version 3.3" -> sources.yml's
    # current.version: "3.3"); the Motor Controller Command Set has none on
    # the page at all, just a publish date -- show it when it genuinely
    # exists rather than presenting a date as if it were a version.
    version = dep.get("current", {}).get("version")
    version_prefix = f"v{version}, " if version else ""

    verdict = {"status": "CURRENT", "detail": f"{version_prefix}{entry['published_date']}, {entry['size_kb']} KB"}

    if do_download and dep["updates"].get("verify_download"):
        with _artifact_dir(dep_id, artifacts_root) as adir:
            archive, err = download_artifact(entry["download_url"], adir)
            if archive is None:
                result["sha256"] = prev.get("sha256")
                state[dep_id] = {**prev, **result}
                return {"status": "SOURCE_UNREACHABLE", "detail": f"document download failed: {err}"}
            sha256 = hashlib.sha256(archive.read_bytes()).hexdigest()
            result["sha256"] = sha256

            prev_hash = prev.get("sha256")
            if metadata_changed:
                verdict = {"status": "SPEC_UPDATED",
                           "detail": f"{version_prefix}{prev.get('published_date')} -> {entry['published_date']} "
                                     f"({prev.get('size_kb')} KB -> {entry['size_kb']} KB)"}
            elif prev_hash and prev_hash != sha256:
                verdict = {"status": "SILENT_REPLACEMENT",
                           "detail": f"{version_prefix}same date/URL/size ({entry['published_date']}) but document "
                                     f"hash changed ({prev_hash[:12]}... -> {sha256[:12]}...)"}
            else:
                verdict = {"status": "CURRENT", "detail": f"{version_prefix}{entry['published_date']}, hash matches"}
    elif metadata_changed:
        verdict = {"status": "SPEC_UPDATED",
                   "detail": f"{version_prefix}{prev.get('published_date')} -> {entry['published_date']} (not hash-verified)"}
        result["sha256"] = prev.get("sha256")
    else:
        result["sha256"] = prev.get("sha256")

    state[dep_id] = {**prev, **result}
    return verdict


def classify_debian_system_package(dep: dict) -> dict:
    """debian/control build/runtime deps carry no version pin -- they always
    track whatever Debian trixie currently ships. So there's no "update
    available" concept to report; the useful signal is which package's
    current trixie version couldn't be resolved at all."""
    result = debian.latest_version(dep)
    per_package = result.get("per_package", {})
    if not per_package:
        return {"status": "manual-check-required", "detail": "no packages configured"}

    unreachable = [pkg for pkg, r in per_package.items() if r["status"] != "ok"]
    if unreachable:
        return {"status": "source-unreachable", "detail": f"could not resolve: {', '.join(sorted(unreachable))}"}

    detail = ", ".join(f"{pkg}={r['latest_version']}" for pkg, r in sorted(per_package.items()))
    return {"status": "current", "detail": detail}


def _local_readme_version(readme_path: Path) -> str | None:
    if not readme_path.exists():
        return None
    matches = re.findall(r"Version:\s*v(\d+\.\d+\.\d+)", readme_path.read_text(encoding="utf-8", errors="replace"))
    return matches[-1] if matches else None


def _embedded_so_version(so_path: Path) -> str | None:
    """Scan a binary's raw bytes for an embedded vX.Y.Z string without
    shelling out to `strings` (not guaranteed present, and this pattern is
    simple enough to find directly)."""
    if not so_path.exists():
        return None
    data = so_path.read_bytes()
    matches = re.findall(rb"v(\d+\.\d+\.\d+)\x00", data)
    if not matches:
        return None
    return matches[0].decode("ascii")


def classify_svbony(dep: dict) -> dict:
    updates = dep["updates"]
    upstream = svbony.fetch_upstream(updates.get("url", svbony.DOWNLOAD_PAGE))
    if upstream["status"] != "ok":
        return {"status": upstream["status"], "detail": upstream.get("detail", "")}

    readme_version = _local_readme_version(REPO_ROOT / updates["readme_path"])
    so_version = _embedded_so_version(REPO_ROOT / updates["so_path"])

    if readme_version is None or so_version is None:
        return {"status": "version-unknown",
                "detail": f"could not read local version (readme={readme_version}, so={so_version})"}
    if readme_version != so_version:
        return {"status": "LOCAL_VERSION_MISMATCH",
                "detail": f"readme.txt says v{readme_version}, libSVBCameraSDK.so embeds v{so_version}"}

    local_version = readme_version
    upstream_version = upstream["version"]
    page_url = updates.get("url", svbony.DOWNLOAD_PAGE)
    detail_suffix = ""
    if upstream.get("restricted"):
        detail_suffix = f" (download restricted; file UUID {upstream.get('file_uuid')}, check {page_url} by hand)"
    if upstream.get("page_date"):
        detail_suffix += f" [page-listed date {upstream['page_date']}, not necessarily the SDK release date]"

    lv, uv = _version_tuple(local_version), _version_tuple(upstream_version)
    if uv > lv:
        return {"status": "UPDATE_AVAILABLE", "detail": f"{local_version} -> {upstream_version}{detail_suffix}"}
    if uv < lv:
        return {"status": "WARNING", "detail": f"local {local_version} is newer than published {upstream_version}{detail_suffix}"}
    return {"status": "CURRENT", "detail": f"{local_version} (readme + .so agree){detail_suffix}"}


def classify(dep: dict, state: dict, do_download: bool, artifacts_root: Path | None) -> dict:
    updates = dep.get("updates")
    if not updates:
        return {"status": "current", "detail": "no update source"}
    provider = updates.get("provider")

    if provider == "manual" and dep["kind"] == "managed-elsewhere":
        return {"status": "current", "detail": updates.get("reason", "managed elsewhere")}

    if provider == "wordpress-acf":
        return classify_wordpress_acf(dep, state, do_download, artifacts_root)

    if provider == "debian" and dep["kind"] == "system-package":
        return classify_debian_system_package(dep)

    if provider == "svbony":
        return classify_svbony(dep)

    if provider == "static-download-page":
        return classify_static_download_page(dep, state, do_download, artifacts_root)

    provider_fn = PROVIDERS.get(provider)
    if provider_fn is None:
        return {"status": "manual-check-required", "detail": f"unknown provider {provider!r}"}

    result = provider_fn(dep)
    status = result["status"]
    if status != "ok":
        return {"status": status, "detail": result.get("reason", "")}

    current_version = map_dependencies.resolve_local_version(dep) or str(dep.get("current", {}).get("version", "")).strip()
    latest = result.get("latest_version")
    if not current_version or current_version.lower() == "unknown":
        return {"status": "version-unknown", "detail": f"latest upstream: {latest}"}
    if latest and latest != current_version:
        return {"status": "update-available", "detail": f"{current_version} -> {latest}"}
    return {"status": "current", "detail": f"at latest ({current_version})"}


def build_report(sources: dict, inventory: dict | None, state: dict, do_download: bool, artifacts_root: Path | None) -> str:
    rows = []
    for dep in sources["dependencies"]:
        verdict = classify(dep, state, do_download, artifacts_root)
        rows.append((dep["id"], dep["kind"], verdict["status"], verdict["detail"]))

    stale_note = ""
    if inventory is None:
        stale_note = "\n**dependencies/inventory.json missing** -- run `map_dependencies.py --write` and commit it.\n"

    lines = [
        "<!-- generated by scripts/dependencies/check_updates.py; do not edit by hand -->",
        f"# {ISSUE_TITLE}",
        "",
        "| Dependency | Kind | Status | Detail |",
        "|---|---|---|---|",
    ]
    for dep_id, kind, status, detail in rows:
        lines.append(f"| `{dep_id}` | {kind} | {status} | {detail} |")

    external_refs = sources.get("external_references", [])
    if external_refs:
        lines += ["", "## External reference material", "",
                   "Protocol docs / manuals with external provenance, not a build dependency "
                   "-- tracked for visibility only, never automatically checked.", "",
                   "| Reference | Path |", "|---|---|"]
        for ref in external_refs:
            lines.append(f"| `{ref['id']}` | `{ref['path']}` |")

    lines.append(stale_note)
    lines.append("GitHub Actions pins are tracked by Dependabot, not this workflow.")
    lines.append(
        "SILENT_REPLACEMENT means the vendor changed an already-published artifact "
        "without bumping its version -- treat this as higher priority than a normal update."
    )
    return "\n".join(lines)


def upsert_issue(body: str, dry_run: bool) -> None:
    if dry_run:
        print(body)
        return
    find = subprocess.run(
        ["gh", "issue", "list", "--search", f'in:title "{ISSUE_TITLE}"', "--state", "all", "--json", "number,title"],
        capture_output=True, text=True,
    )
    number = None
    if find.returncode == 0:
        for issue in json.loads(find.stdout or "[]"):
            if issue["title"] == ISSUE_TITLE:
                number = issue["number"]
                break

    tmp = REPO_ROOT / "dependencies" / ".issue-body.tmp.md"
    tmp.write_text(body)
    try:
        if number is None:
            subprocess.run(["gh", "issue", "create", "--title", ISSUE_TITLE, "--body-file", str(tmp)], check=True)
        else:
            subprocess.run(["gh", "issue", "edit", str(number), "--body-file", str(tmp)], check=True)
    finally:
        tmp.unlink(missing_ok=True)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dry-run", action="store_true", help="print the report instead of updating a GitHub issue")
    parser.add_argument("--no-download", action="store_true", help="skip archive download/hash verification (metadata only)")
    parser.add_argument("--artifacts-dir", type=Path, default=None,
                         help="keep downloaded archives here (for CI to upload as a build artifact) instead of a temp dir")
    args = parser.parse_args()

    sources = load_yaml(SOURCES_PATH)
    inventory = json.loads(INVENTORY_PATH.read_text()) if INVENTORY_PATH.exists() else None
    state = load_state()
    body = build_report(sources, inventory, state, do_download=not args.no_download, artifacts_root=args.artifacts_dir)
    save_state(state)
    upsert_issue(body, args.dry_run)
    return 0


if __name__ == "__main__":
    sys.exit(main())
